### ISSUE TITLE
sampler is not in the sampler registry issue

### ISSUE THREAD

**Issue by dong-ma-zi** [LL3RD/ACFormer#2]
~~~
fatal: not a git repository (or any parent up to mount point /home)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "tools/train.py", line 200, in <module>
    main()
  File "tools/train.py", line 188, in main
    train_detector(
  File "/home/data1/my/Project/nucleiDetCls/ACFormer/ssod/apis/train.py", line 70, in train_detector
    data_loaders = [
  File "/home/data1/my/Project/nucleiDetCls/ACFormer/ssod/apis/train.py", line 71, in <listcomp>
    build_dataloader(
  File "/home/data1/my/Project/nucleiDetCls/ACFormer/ssod/datasets/builder.py", line 68, in build_dataloader
    build_sampler(sampler_cfg, default_args=default_sampler_cfg)
  File "/home/data1/my/Project/nucleiDetCls/ACFormer/ssod/datasets/builder.py", line 40, in build_sampler
    return build_from_cfg(cfg, SAMPLERS, default_args)
  File "/home/my/.conda/envs/ACFormer/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'sampler is not in the sampler registry'
~~~

I'm not very familiar with the mechanics of mmdetection, can you help me with this?

**Comment by dddddddck** [comment]
I also have this problem, have you solved it？

**Comment by LL3RD** [comment]
Please try using distributed training script _bash tools/dist_train.sh {config_file} 1_ instead of using _python train.py_

**Comment by tyloocifer** [comment]
if you want to use train.py you should build your dataloader with GroupSampler or something else,
